//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_Book_Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PHONE_BOOK_DBEntities : DbContext
    {
        public PHONE_BOOK_DBEntities()
            : base("name=PHONE_BOOK_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_PHONE_BOOK> T_PHONE_BOOK { get; set; }
        public virtual DbSet<T_PHONE_TYPE> T_PHONE_TYPE { get; set; }
    
        public virtual int P_INSERT_PHONE_BOOK(string nAME, string sURNAME, Nullable<int> iD_PHONE_TYPE, Nullable<System.DateTime> dELETED_DATE, Nullable<System.DateTime> mODIFIED_DATE, Nullable<System.DateTime> iNSERTED_DATE)
        {
            var nAMEParameter = nAME != null ?
                new ObjectParameter("NAME", nAME) :
                new ObjectParameter("NAME", typeof(string));
    
            var sURNAMEParameter = sURNAME != null ?
                new ObjectParameter("SURNAME", sURNAME) :
                new ObjectParameter("SURNAME", typeof(string));
    
            var iD_PHONE_TYPEParameter = iD_PHONE_TYPE.HasValue ?
                new ObjectParameter("ID_PHONE_TYPE", iD_PHONE_TYPE) :
                new ObjectParameter("ID_PHONE_TYPE", typeof(int));
    
            var dELETED_DATEParameter = dELETED_DATE.HasValue ?
                new ObjectParameter("DELETED_DATE", dELETED_DATE) :
                new ObjectParameter("DELETED_DATE", typeof(System.DateTime));
    
            var mODIFIED_DATEParameter = mODIFIED_DATE.HasValue ?
                new ObjectParameter("MODIFIED_DATE", mODIFIED_DATE) :
                new ObjectParameter("MODIFIED_DATE", typeof(System.DateTime));
    
            var iNSERTED_DATEParameter = iNSERTED_DATE.HasValue ?
                new ObjectParameter("INSERTED_DATE", iNSERTED_DATE) :
                new ObjectParameter("INSERTED_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_INSERT_PHONE_BOOK", nAMEParameter, sURNAMEParameter, iD_PHONE_TYPEParameter, dELETED_DATEParameter, mODIFIED_DATEParameter, iNSERTED_DATEParameter);
        }
    }
}
